#!/usr/bin/env python3
"""生成器の入力が Figma の機械書き出しだけかを見る（記録層の廃止・2026-08-29）。

aub-familywalk の実害: `gen_chrome_specs.py` が **AI の手書き記録**
（design/values/chrome.json）を読んで `chrome_specs.g.dart` を吐いていた。
誤った手書きの値が「自動生成。手で編集しない。」というヘッダを付けて出てくるので、
下流からは機械生成の値と見分けが付かない（**誤りの洗浄**）。
実測では、手書きの層から8件の値の誤りが出たのに対し、書き出しから
機械生成した層は0件だった。

## この検査が捕まえるもの

- `design/gen/*.py` の中の文字列リテラルに、`design/values` /（figma/ 配下でない）
  `.json` の読み取りが現れること
- テスト・実装が `design/values` を読んでいること（照合相手は書き出しだけ、の移行検査）

## この検査が捕まえないもの

- 動的に組み立てたパス（変数連結）。文字列リテラルしか見ない
- 生成器のロジックの誤り（べき等性は design/gen/verify.py の領域）
- 確かめた方法: --self-test（values を読む生成器を仕込んで落ちること）

## 使い方（案件のルートで）

    python3 design/harness/tools/gen_input_check.py \\
        [--gen design/gen] [--tests test] [--allow figma/ design/figma/]
"""

import argparse
import re
import sys
from pathlib import Path

#: 読み取りの気配。open(...) / read_text / json.load(open(...)) / Path(...)
#: `File(...)` `readAsString` は Dart、`readFileSync` は Node（2026-09-02 に追加。
#: それまで Python の書き方しか見ておらず、**Dart の生成器が素通り**していた）。
READ_RX = re.compile(
    r"""(?:open|read_text|Path|load|loads|File|readAsString\w*|readFileSync)"""
    r"""\s*\(?[^)\n]*?['"]([\w./-]+\.(?:json|md|csv|yaml|yml))['"]""")

#: 手書きの記録層。ここを読む生成器・テストは誤りの洗浄になる
BANNED = ("design/values",)

#: 生成器として読む拡張子（2026-09-02）。それまで `.py` だけを見ており、
#: **Flutter で最も自然な生成器の言語（Dart）と Node が素通り**していた。
GEN_SUFFIXES = (".py", ".dart", ".mjs", ".js", ".ts", ".sh")

#: 「自動生成」を名乗る印。
CLAIM_RX = re.compile(r"自動生成|手で編集しない|GENERATED|generated by|DO NOT EDIT",
                      re.IGNORECASE)
#: 生成器の申告。`生成器: design/gen/gen_colors.py` のような行。
PRODUCER_RX = re.compile(
    r"(?:生成器|生成スクリプト|generator)\s*[:：]\s*([\w./\\-]+)")


def reads_in(path):
    out = []
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return out
    for i, line in enumerate(text.splitlines(), 1):
        if line.strip().startswith("#") or "gen-input-ignore" in line:
            continue
        for m in READ_RX.finditer(line):
            out.append((i, m.group(1)))
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description="生成器・テストの入力が書き出しだけか")
    ap.add_argument("--gen", type=Path, default=Path("design/gen"))
    ap.add_argument("--tests", type=Path, default=Path("test"))
    ap.add_argument("--allow", nargs="*",
                    default=["figma/", "design/figma/", "gen/", "design/gen/"],
                    help="生成器が読んでよいパスの接頭辞（書き出しと生成器自身の中間物）")
    ap.add_argument("--root", type=Path, default=Path("."))
    ap.add_argument("--claims", nargs="*",
                    default=["lib/**/*.dart", "lib/**/*.ts", "src/**/*.ts",
                             "src/**/*.css"],
                    help="「自動生成」を名乗るファイルを探す範囲")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)

    if args.self_test:
        return self_test()

    problems = []

    # 1) 生成器: 許可された接頭辞以外の読み取りを全部拾う（許可リスト方式）
    gen_files = []
    if args.gen.exists():
        gen_files = [f for f in sorted(args.gen.rglob("*"))
                     if f.is_file() and f.suffix in GEN_SUFFIXES]
        for f in gen_files:
            for lineno, p in reads_in(f):
                name = p.split("/")[-1]
                ok = (any(p.startswith(a) or f"/{a}" in p for a in args.allow)
                      or "/" not in p)   # 素のファイル名は gen 内の中間物とみなす
                if any(b in p for b in BANNED):
                    problems.append(f"  {f}:{lineno}: 手書きの記録層を読んでいます: {p}")
                elif not ok:
                    problems.append(f"  {f}:{lineno}: 書き出し以外を入力にしています: {p}"
                                    f"（許可: {args.allow}）")

    # 2) テスト・実装: 記録層の参照が残っていないか（移行検査）
    for base in (args.tests, Path("lib")):
        if not base.exists():
            continue
        for f in sorted(base.rglob("*")):
            if f.suffix not in (".dart", ".py", ".ts", ".tsx", ".js", ".mjs"):
                continue
            try:
                text = f.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for i, line in enumerate(text.splitlines(), 1):
                if "gen-input-ignore" in line:
                    continue
                if any(b in line for b in BANNED) and (
                        ".json" in line or "values" in line.lower()):
                    if "design/values" in line:
                        problems.append(
                            f"  {f}:{i}: 記録層（design/values）を照合相手にしています。"
                            f"照合相手は figma/ の書き出しだけです")

    # 3) **「自動生成」と名乗るなら、生成器が実在すること**（2026-09-02 新設）。
    #    planttalk の実害: lib/theme/ の5ファイルが「このファイルは
    #    PlantTalk Design System から自動生成されています。手で編集しないこと。」と
    #    宣言しているのに、**生成器が存在しない**。gen_input_check が生まれた理由
    #    （誤りの洗浄）の最も直接的な事例が、この道具から見えていなかった
    problems += claim_problems(args.claims, args.root)

    print(f"生成器の入力: {len(gen_files)} ファイルを読みました"
          + ("" if gen_files else "（**0件。生成器が無いか、置き場が違います**）"))
    if problems:
        print("生成器・照合の入力に、手で書いた層が混ざっています"
              "（2026-08-29 記録層の廃止）:", file=sys.stderr)
        print("\n".join(sorted(set(problems))), file=sys.stderr)
        return 1
    print("OK: 生成器と照合の入力は Figma の書き出しだけです。")
    return 0


def claim_problems(globs, root):
    """「自動生成」を名乗るファイルに、実在する生成器の申告を求める。

    名乗るだけなら誰でもできる。**申告が無い／指した先が無い**なら、
    そのファイルは手書きの可能性がある。
    """
    out = []
    for g in globs:
        for f in sorted(Path(root).glob(g)):
            if not f.is_file() or f.suffix not in (".dart", ".ts", ".tsx", ".css", ".js"):
                continue
            head = "\n".join(
                f.read_text(encoding="utf-8", errors="ignore").splitlines()[:15])
            if not CLAIM_RX.search(head):
                continue
            m = PRODUCER_RX.search(head)
            if not m:
                out.append(f"  {f}: 「自動生成」と名乗っていますが、**生成器の申告が"
                           f"ありません**。冒頭に `生成器: <パス>` を書いてください"
                           f"（申告できないなら、それは生成物ではありません）")
                continue
            if not (Path(root) / m.group(1)).exists():
                out.append(f"  {f}: 申告された生成器がありません: {m.group(1)}"
                           f"（**手で書いた値が「自動生成」のヘッダを付けて"
                           f"流れています**）")
    return out


def self_test():
    import tempfile, os
    ok = True
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        gen = root / "design/gen"
        gen.mkdir(parents=True)
        (root / "test").mkdir()
        cwd = os.getcwd()
        os.chdir(root)
        try:
            (gen / "gen_good.py").write_text(
                'DOC = json.load(open("design/figma/components.json"))\n',
                encoding="utf-8")
            if main([]) != 0:
                print("self-test NG: 書き出しだけなのに落ちた"); ok = False

            (gen / "gen_bad.py").write_text(
                'DOC = json.load(open("design/values/chrome.json"))\n',
                encoding="utf-8")
            if main([]) != 1:
                print("self-test NG: 記録層を読む生成器で落ちなかった"); ok = False
            (gen / "gen_bad.py").unlink()

            (root / "test/t.dart").write_text(
                "final doc = File('design/values/header.json');\n",
                encoding="utf-8")
            if main([]) != 1:
                print("self-test NG: 記録層を読むテストで落ちなかった"); ok = False
            (root / "test/t.dart").write_text(
                "final doc = File('design/figma/frames.json');\n", encoding="utf-8")
            if main([]) != 0:
                print("self-test NG: 書き出しを読むテストなのに落ちた"); ok = False

            # --- 2026-09-02 に足した範囲 ---------------------------------
            # Dart の生成器（Flutter で最も自然な言語）が素通りしていた
            (gen / "gen_theme.dart").write_text(
                "final doc = File('design/values/chrome.json');\n", encoding="utf-8")
            if main([]) != 1:
                print("self-test NG: Dart の生成器が記録層を読んでも落ちなかった"); ok = False
            (gen / "gen_theme.dart").unlink()

            # 入れ子の生成器が素通りしていた
            (gen / "theme").mkdir()
            (gen / "theme" / "gen_sem.py").write_text(
                'D = json.load(open("design/values/sem.json"))\n', encoding="utf-8")
            if main([]) != 1:
                print("self-test NG: 入れ子の生成器が素通りした"); ok = False
            (gen / "theme" / "gen_sem.py").unlink()

            # 「自動生成」と名乗るのに生成器の申告が無い
            (root / "lib" / "theme").mkdir(parents=True)
            claim = root / "lib" / "theme" / "sem.dart"
            claim.write_text(
                "// このファイルは自動生成されています。手で編集しないこと。\n"
                "const x = 1;\n", encoding="utf-8")
            if main([]) != 1:
                print("self-test NG: 生成器の申告が無い『自動生成』を通した"); ok = False

            # 申告があるが実在しない
            claim.write_text(
                "// 自動生成。手で編集しない。\n"
                "// 生成器: design/gen/gen_sem.py\n const x = 1;\n", encoding="utf-8")
            if main([]) != 1:
                print("self-test NG: 実在しない生成器の申告を通した"); ok = False

            # 申告があり実在する
            (gen / "gen_sem.py").write_text(
                'D = json.load(open("design/figma/variables.json"))\n',
                encoding="utf-8")
            if main([]) != 0:
                print("self-test NG: 正しい申告で落ちた"); ok = False
        finally:
            os.chdir(cwd)
    print("self-test:", "OK" if ok else "NG")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
